name: backend-ci-cd
on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - "docker-compose.prod.yml"
      - ".github/workflows/backend.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/calendrier-backend:${{ github.sha }} ./backend
          docker push ghcr.io/${{ github.repository_owner }}/calendrier-backend:${{ github.sha }}
      - name: Export tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/apps/calendrier/"
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/apps/calendrier
            sed -i "s|^IMAGE_TAG=.*|IMAGE_TAG=${{ env.IMAGE_TAG }}|" .env.prod || echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> .env.prod
            docker login ghcr.io -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}
            docker compose -f docker-compose.prod.yml --env-file .env.prod pull backend
            docker compose -f docker-compose.prod.yml --env-file .env.prod up -d backend
            docker compose -f docker-compose.prod.yml --env-file .env.prod exec -T backend python manage.py migrate
