version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 40
    restart: unless-stopped

  backend:
    # L'image est publiée par le workflow backend.yml sur GHCR
    image: ghcr.io/${REPO_OWNER:-blues1961}/calendrier-backend:${IMAGE_TAG:-latest}
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      # Exposé seulement en local pour le reverse proxy Apache
      - "127.0.0.1:8002:8000"
    volumes:
      # Si tu fais collectstatic, laisse un dossier pour que ce soit persistant
      - /opt/apps/calendrier/staticfiles:/app/staticfiles
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -H 'Host: cal-api.mon-site.ca' -H 'X-Forwarded-Proto: https' http://localhost:8000/api/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

networks:
  internal:

volumes:
  db_data_prod:
