name: cal_prod

services:
  db:
    networks: [appnet]

  backend:
    networks: [appnet, edge]
    labels:
      - traefik.enable=true
      - traefik.docker.network=edge
      - traefik.http.routers.cal_api.rule=Host(`cal-api.mon-site.ca`)
      - traefik.http.routers.cal_api.entrypoints=web
      - traefik.http.services.cal_api.loadbalancer.server.port=8000

  frontend:
    networks: [edge]
    labels:
      - traefik.enable=true
      - traefik.docker.network=edge
      - traefik.http.routers.cal_front.rule=Host(`cal.mon-site.ca`)
      - traefik.http.routers.cal_front.entrypoints=web
      - traefik.http.services.cal_front.loadbalancer.server.port=80

networks:
  appnet: {}
  edge:
    external: true
