services:
  db:
    image: postgres:16
    container_name: ${APP_SLUG}_db_${APP_ENV}
    env_file:
      - .env.dev
      - .env.dev.local
    ports:
      - "${DEV_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 40

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ${APP_SLUG}_backend_${APP_ENV}
    env_file:
      - .env.dev
      - .env.dev.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - "${DEV_API_PORT}:8000"
    command: ["bash","-lc","python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

  vite:
    image: node:20-bookworm-slim
    container_name: ${APP_SLUG}_vite_${APP_ENV}
    working_dir: /app
    env_file:
      - .env.dev
      - .env.dev.local
    environment:
      VITE_API_BASE: "/api"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "${DEV_VITE_PORT}:5173"  # Vite dev server (HMR)
    command: ["bash","-lc","( [ -d node_modules ] && [ -f node_modules/.ready ] ) || (npm ci || npm install; touch node_modules/.ready); npm run dev -- --host 0.0.0.0 --port 5173"]
    restart: unless-stopped

volumes:
  pgdata:
    name: ${APP_SLUG}_${APP_ENV}_pgdata
  node_modules:
    name: ${APP_SLUG}_${APP_ENV}_node_modules
