name: backend-ci-cd
on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/backend.yml"
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "backend workflow smoke ok"
