name: frontend-ci-cd

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json  # Assurez-vous que ce fichier existe et est au bon emplacement

      - name: Install & build (Vite)
        working-directory: frontend
        env:
          VITE_API_BASE: https://cal-api.mon-site.ca
        run: |
          npm ci
          npm run build

      - name: Prepare remote dir
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/cal.mon-site.ca/public_html
            sudo chown $USER:$USER /var/www/cal.mon-site.ca/public_html

      - name: Rsync dist/ to server
        run: |
          rsync -avz --delete frontend/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/cal.mon-site.ca/public_html/

    concurrency:
      group: deploy-frontend
      cancel-in-progress: true
